name: "Podcase Generator"
author: "Luis"
description: "Generates a feed for a podcast from a yaml file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icom: "git-branch"
  color: "red"
inputs: 
  email:
    description: true
    default: ${{github.actor}}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}